name: ssl_mimosa
channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - ca-certificates=2025.6.15
  - ld_impl_linux-64=2.43
  - libffi=3.4.6
  - libgcc=15.1.0
  - libgcc-ng=15.1.0
  - libgomp=15.1.0
  - liblzma=5.8.1
  - liblzma-devel=5.8.1
  - libsqlite=3.46.0
  - libzlib=1.2.13
  - ncurses=6.5
  - openssl=3.5.1
  - pip=21.2.4
  - python=3.9.7
  - readline=8.2
  - sqlite=3.46.0
  - tk=8.6.13
  - wheel=0.45.1
  - xz=5.8.1
  - xz-gpl-tools=5.8.1
  - xz-tools=5.8.1
  - zlib=1.2.13
  - pip:
      - absl-py==1.0.0
      - aiohttp==3.8.1
      - aiosignal==1.2.0
      - anyio==3.5.0
      - argon2-cffi==21.3.0
      - argon2-cffi-bindings==21.2.0
      - asttokens==2.0.5
      - async-timeout==4.0.2
      - attrs==21.4.0
      - babel==2.9.1
      - backcall==0.2.0
      - beautifulsoup4==4.10.0
      - bleach==4.1.0
      - cachetools==5.0.0
      - certifi==2025.6.15
      - cffi==1.15.0
      - charset-normalizer==2.0.12
      - contourpy==1.3.0
      - cycler==0.12.1
      - debugpy==1.6.0
      - decorator==5.1.1
      - defusedxml==0.7.1
      - entrypoints==0.4
      - executing==0.8.3
      - filelock==3.18.0
      - fonttools==4.59.1
      - frozenlist==1.3.0
      - fsspec==2022.2.0
      - future==0.18.2
      - google-auth==2.6.2
      - google-auth-oauthlib==0.4.6
      - grpcio==1.74.0
      - h5py==3.6.0
      - idna==3.3
      - imageio==2.16.1
      - importlib-metadata==4.11.3
      - importlib-resources==6.5.2
      - ipykernel==6.9.2
      - ipython==8.2.0
      - ipython-genutils==0.2.0
      - jedi==0.18.1
      - jinja2==3.1.1
      - json5==0.9.6
      - jsonschema==4.4.0
      - jupyter-client==7.1.2
      - jupyter-core==4.9.2
      - jupyter-server==1.15.6
      - jupyterlab==3.3.2
      - jupyterlab-pygments==0.1.2
      - jupyterlab-server==2.11.2
      - kiwisolver==1.4.7
      - lightning-utilities==0.14.3
      - markdown==3.3.6
      - markupsafe==2.1.1
      - matplotlib==3.9.4
      - matplotlib-inline==0.1.3
      - mistune==0.8.4
      - mpmath==1.3.0
      - multidict==6.0.2
      - nbclassic==0.3.7
      - nbclient==0.5.13
      - nbconvert==6.4.5
      - nbformat==5.2.0
      - nest-asyncio==1.5.4
      - networkx==2.7.1
      - notebook==6.4.10
      - notebook-shim==0.1.0
      - numpy==1.24.4
      - nvidia-cublas-cu12==12.6.4.1
      - nvidia-cuda-cupti-cu12==12.6.80
      - nvidia-cuda-nvrtc-cu12==12.6.77
      - nvidia-cuda-runtime-cu12==12.6.77
      - nvidia-cudnn-cu12==9.5.1.17
      - nvidia-cufft-cu12==11.3.0.4
      - nvidia-cufile-cu12==1.11.1.6
      - nvidia-curand-cu12==10.3.7.77
      - nvidia-cusolver-cu12==11.7.1.2
      - nvidia-cusparse-cu12==12.5.4.2
      - nvidia-cusparselt-cu12==0.6.3
      - nvidia-nccl-cu12==2.26.2
      - nvidia-nvjitlink-cu12==12.6.85
      - nvidia-nvtx-cu12==12.6.77
      - oauthlib==3.2.0
      - packaging==21.3
      - pandas==2.3.0
      - pandocfilters==1.5.0
      - parso==0.8.3
      - pexpect==4.8.0
      - pickleshare==0.7.5
      - pillow==11.3.0
      - prometheus-client==0.13.1
      - prompt-toolkit==3.0.28
      - protobuf==6.31.1
      - psutil==5.9.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - pyasn1==0.4.8
      - pyasn1-modules==0.2.8
      - pycparser==2.21
      - pydeprecate==0.3.1
      - pygments==2.11.2
      - pyparsing==3.0.7
      - pyrsistent==0.18.1
      - python-dateutil==2.8.2
      - pytorch-lightning==1.9.0
      - pytz==2022.1
      - pywavelets==1.3.0
      - pyyaml==6.0
      - pyzmq==22.3.0
      - requests==2.27.1
      - requests-oauthlib==1.3.1
      - rsa==4.8
      - runstats==2.0.0
      - scikit-image==0.19.2
      - scipy==1.8.0
      - send2trash==1.8.0
      - setuptools==59.5.0
      - six==1.16.0
      - sniffio==1.2.0
      - soupsieve==2.3.1
      - stack-data==0.2.0
      - sympy==1.14.0
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - tensorboard-plugin-wit==1.8.1
      - terminado==0.13.3
      - testpath==0.6.0
      - tifffile==2022.3.16
      - torch==2.7.1
      - torchaudio==2.7.1
      - torchkbnufft==1.3.0
      - torchmetrics==0.7.2
      - torchvision==0.22.1
      - tornado==6.1
      - tqdm==4.63.0
      - traitlets==5.1.1
      - triton==3.3.1
      - typing-extensions==4.14.0
      - tzdata==2025.2
      - urllib3==1.26.9
      - wcwidth==0.2.5
      - webencodings==0.5.1
      - websocket-client==1.3.1
      - werkzeug==2.0.3
      - yarl==1.7.2
      - zipp==3.7.0